# List available commands
default:
    @just --list

# Create or edit a secret file (usage: just create-secret filename.age)
create-secret filename:
    nix run github:ryantm/agenix -- -e {{filename}}